### ISSUE TITLE
Kanał z podziękowaniami

### ISSUE THREAD

**Issue by Dersivative** [bopke/CSRVbot#12]
---
Propozycja: Osobny kanał z niezatwierdzonymi podziękowaniami

---

**Problem**
Mnóstwo thxów pozostaje niezatwierdzonych, co skutkuje żebractwem i ogólnym spamem prośbami o sprawdzenie na różnych kanałach.

**Rozwiązanie**
Utworzenie kanału z duplikatami niesprawdzonych THXów:
* Trafiają tam tylko niesprawdzone podziękowania - bot usuwa wiadomość po potwierdzeniu/odrzuceniu.
* Oprócz samego embeda jest też link do wiadomości wywołującej !thx.

W ten sposób otrzymujemy listę thxów do sprawdzenia wraz z linkami do adekwatnego miejsca w dyskusji.

**Comment by CDFN** [comment]
To prosze napisać że super propozycja

**Comment by Toranktto** [comment]
Uważam że to bardzo dobry pomysł.

**Comment by ghost** [comment]
Tak jestem za! Bez tego ludzie piszą na pv wysyłając linki do podziękowań lub niepotrzebnie oznaczają osoby uprawnione do zatwierdzaniach owych próśb.

**Comment by Dersivative** [comment]
> 
> 
> Tak jestem za! Bez tego ludzie piszą na pv wysyłając linki do podziękowań lub niepotrzebnie oznaczają osoby uprawnione do zatwierdzaniach owych próśb.

Proszę zablokować DM.

**Comment by CDFN** [comment]
> > Tak jestem za! Bez tego ludzie piszą na pv wysyłając linki do podziękowań lub niepotrzebnie oznaczają osoby uprawnione do zatwierdzaniach owych próśb.
> 
> Proszę zablokować DM.

A co z oznaczaniem na serwerze? Argument z czapy

**Comment by Dersivative** [comment]
> 
> 
> > > Tak jestem za! Bez tego ludzie piszą na pv wysyłając linki do podziękowań lub niepotrzebnie oznaczają osoby uprawnione do zatwierdzaniach owych próśb.
> > 
> > 
> > Proszę zablokować DM.
> 
> A co z oznaczaniem na serwerze? Argument z czapy

Proszę zablokować powiadomienia z oznaczeń.

**Comment by sh3zb0t** [comment]
+1 *bump*

**Comment by thatbakamono** [comment]
Doskonała propozycja napisana przez doskonałego człowieka, nic tylko srać do gniazda

**Comment by ghost** [comment]
Poparcie jak na prezydenta idzie w stronę kanału do oczekujących podziękowań

**Comment by TakToJa123** [comment]
Yes

**Comment by Adenser** [comment]
moze zrobilibyscie
pr
a nie sracie
jak dzieci
pozdrawiam
gdyby bot byl w ruscie
to byloby prosciej

**Comment by CDFN** [comment]
> gdyby bot byl w ruscie
> to byloby prosciej

ale jest w ludzkim języku 👎

**Comment by bopke** [comment]
`Trafiają tam tylko niesprawdzone podziękowania - bot usuwa wiadomość po potwierdzeniu/odrzuceniu.`
Edytujemy wiadomość zamiast usuwać, żeby był lepszy pogląd kto, co i kiedy.

Dodane =)

**Comment by Dersivative** [comment]
Top-tier programmer. 3/10, would recommend.
